FROM dr_py_base:latest

WORKDIR /app

# COPY . /app

#VOLUME ["/app/prediction_result"]
# RUN mkdir -p "/app/prediction_result/"

# CMD ["python", "dr_model_prediction_faster_record_rain_AWS.py"]
# CMD ["python", "try_new_folder.py"]
# CMD ["sh", "-c", "python python1.py && python python2.py"]