FROM python:3.12

WORKDIR /app

RUN apt-get clean && apt-get update && apt-get install -y \
   libmariadb-dev \
   gcc \
   tk\
   cron\
   vim\
   proj-bin \
   poppler-utils

RUN pip install --upgrade pip

COPY requirement.txt /app

RUN pip install --no-cache-dir -r requirement.txt

ENV PYTHONUNBUFFERED=1
